export const GET_TRANSLATION_REQUEST = "GET_TRANSLATION_REQUEST";
export const GET_TRANSLATION_SUCCESS = "GET_TRANSLATION_SUCCESS";
export const GET_TRANSLATION_FAILURE = "GET_TRANSLATION_FAILURE";

export const SET_SOURCE_LANG = "SET_SOURCE_LANG";
export const SET_TARGET_LANG = "SET_TARGET_LANG";
